### ISSUE TITLE
Does not show effect on python file on vscode

### ISSUE THREAD

**Issue by mysteriousHerb** [idleberg/vscode-hopscotch#9] opened 2018-08-04 07:45 UTC
![image](https://user-images.githubusercontent.com/13511170/43673904-8cfd4dfc-97c2-11e8-91ce-d47bd03087fa.png)

Hi, I am really eager to get this colour working on my VScode. However, it doesnt seem to apply everywhere other than changing the background and the string colour. I have disabled other colour-chaning plugins, but no luck so far.

**Comment by idleberg** [comment] 2018-08-04 14:45
This is a duplicate of #2, please always search issues before posting new ones! 

Coloring parts of the syntax is within the domain of the syntax definition, not the color scheme.

More specifically:

- color schemes define colors for categories such as `function`, `class`, `variable`, `operator`, `string`, `integer` etc.
- syntax definitions define patterns that assign the syntax to those categories mentioned above

That said, your code-example will most likely look similar with most other schemes.

**Closed as completed by idleberg** 2018-08-04 14:45 UTC
Labels: duplicate
